version: '3.7'

networks:
  hello-world-net:
    driver: bridge

services:

  hello-world:
    image: hello-world:latest
    environment:
      - LOG_LEVEL=INFO
    ports:
      - "8000:8000"
    restart: on-failure
    networks: 
      - hello-world-net
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
